### ISSUE TITLE
Query Regions a Given Distance from a Point

### ISSUE THREAD

**Issue by kevin-bruhwiler** [Project-Sustain/aperture-client#100]
We need to be able to run queries based on regions that satisfy some query predicate e.g. regions that are >30min drive away from a hospital.

**Comment by menuka94** [comment]
I will implement this is in gRPC.

**Comment by kevin-bruhwiler** [comment]
I appreciate your enthusiasm, but you may want to hold off for a little while. We will definitely need that at some point, but first we need to figure out how we're representing those queries on the front-end (we need to come up with something that's visually appealing and makes intuitive sense to users). I'm also under the impression that we're restructuring the servers, so we'll need to take care of that first as well.
