### ISSUE TITLE
Add Collections to Existing Layer

### ISSUE THREAD

**Issue by falarrieu** [Project-Sustain/aperture-client#603]

**Comment by falarrieu** [comment]
Current implementation ideas includes creating a single pipeline for multiple datasets of the same shape and/or setting up SQS to pass multiple collections under one shape.

**Comment by tmoleary21** [comment]
Taking this on starting 11/15. Plan is to create a HashTable/Map to store the incoming data and associate data from the different datasets at the same location together. It will be accessible at least to all of the Deck.GL GeoJSON layer callback functions (like getFillColor or onClick).

Uncertain of whether to have one HashTable or one per section/quadrant. Right now it seems like just having one would be best so we don't have to check 4+ tables when retrieving the data in the future.
